/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace HealthRecords {
      
    export type AccessRecordStruct = {id: BigNumberish, patient: AddressLike, doctor: AddressLike, accessType: BigNumberish, status: BigNumberish, requestedAt: BigNumberish, grantedAt: BigNumberish, expiresAt: BigNumberish, flaggedForReview: boolean, reasonHash: BytesLike}

    export type AccessRecordStructOutput = [id: bigint, patient: string, doctor: string, accessType: bigint, status: bigint, requestedAt: bigint, grantedAt: bigint, expiresAt: bigint, flaggedForReview: boolean, reasonHash: string] & {id: bigint, patient: string, doctor: string, accessType: bigint, status: bigint, requestedAt: bigint, grantedAt: bigint, expiresAt: bigint, flaggedForReview: boolean, reasonHash: string }
  

    export type MedicalRecordStruct = {id: BigNumberish, patient: AddressLike, fileHash: BytesLike, metadataHash: BytesLike, createdAt: BigNumberish}

    export type MedicalRecordStructOutput = [id: bigint, patient: string, fileHash: string, metadataHash: string, createdAt: bigint] & {id: bigint, patient: string, fileHash: string, metadataHash: string, createdAt: bigint }
  
    }

  export interface HealthRecordsInterface extends Interface {
    getFunction(nameOrSignature: "EMERGENCY_ACCESS_DURATION" | "MAX_EMERGENCY_REASON_LENGTH" | "activeEmergencyAccessId" | "activeStandardAccessId" | "admin" | "anchorMedicalRecord" | "consent" | "expireEmergencyAccess" | "flagForReview" | "getAccessRecord" | "getMedicalRecord" | "getPatientRecordIds" | "grantAccess" | "hasAccess" | "latestPendingRequestId" | "logRecordAccess" | "nextAccessId" | "nextRecordId" | "recordIdByHash" | "rejectAccessRequest" | "requestAccess" | "requestEmergencyAccess" | "revokeAccess" | "setVerifiedProvider" | "transferAdmin" | "verifiedProviders"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AccessGranted" | "AccessRequestRejected" | "AccessRequested" | "AccessRevoked" | "AdminTransferred" | "EmergencyAccessExpired" | "EmergencyAccessFlagged" | "EmergencyAccessGranted" | "MedicalRecordAnchored" | "ProviderVerificationUpdated" | "RecordAccessed"): EventFragment;

    encodeFunctionData(functionFragment: 'EMERGENCY_ACCESS_DURATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_EMERGENCY_REASON_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'activeEmergencyAccessId', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'activeStandardAccessId', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'anchorMedicalRecord', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'consent', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'expireEmergencyAccess', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'flagForReview', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAccessRecord', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMedicalRecord', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPatientRecordIds', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantAccess', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'hasAccess', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'latestPendingRequestId', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'logRecordAccess', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextAccessId', values?: undefined): string;
encodeFunctionData(functionFragment: 'nextRecordId', values?: undefined): string;
encodeFunctionData(functionFragment: 'recordIdByHash', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'rejectAccessRequest', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'requestAccess', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'requestEmergencyAccess', values: [AddressLike, string]): string;
encodeFunctionData(functionFragment: 'revokeAccess', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setVerifiedProvider', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'transferAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'verifiedProviders', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'EMERGENCY_ACCESS_DURATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_EMERGENCY_REASON_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'activeEmergencyAccessId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'activeStandardAccessId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'anchorMedicalRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'consent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'expireEmergencyAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'flagForReview', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAccessRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMedicalRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPatientRecordIds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'latestPendingRequestId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'logRecordAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextAccessId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextRecordId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordIdByHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectAccessRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestEmergencyAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setVerifiedProvider', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifiedProviders', data: BytesLike): Result;
  }

  
    export namespace AccessGrantedEvent {
      export type InputTuple = [accessId: BigNumberish, patient: AddressLike, doctor: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [accessId: bigint, patient: string, doctor: string, timestamp: bigint];
      export interface OutputObject {accessId: bigint, patient: string, doctor: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AccessRequestRejectedEvent {
      export type InputTuple = [accessId: BigNumberish, patient: AddressLike, doctor: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [accessId: bigint, patient: string, doctor: string, timestamp: bigint];
      export interface OutputObject {accessId: bigint, patient: string, doctor: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AccessRequestedEvent {
      export type InputTuple = [accessId: BigNumberish, doctor: AddressLike, patient: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [accessId: bigint, doctor: string, patient: string, timestamp: bigint];
      export interface OutputObject {accessId: bigint, doctor: string, patient: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AccessRevokedEvent {
      export type InputTuple = [accessId: BigNumberish, patient: AddressLike, doctor: AddressLike, emergencyAccess: boolean, timestamp: BigNumberish];
      export type OutputTuple = [accessId: bigint, patient: string, doctor: string, emergencyAccess: boolean, timestamp: bigint];
      export interface OutputObject {accessId: bigint, patient: string, doctor: string, emergencyAccess: boolean, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AdminTransferredEvent {
      export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
      export type OutputTuple = [previousAdmin: string, newAdmin: string];
      export interface OutputObject {previousAdmin: string, newAdmin: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyAccessExpiredEvent {
      export type InputTuple = [accessId: BigNumberish, doctor: AddressLike, patient: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [accessId: bigint, doctor: string, patient: string, timestamp: bigint];
      export interface OutputObject {accessId: bigint, doctor: string, patient: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyAccessFlaggedEvent {
      export type InputTuple = [accessId: BigNumberish, flaggedBy: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [accessId: bigint, flaggedBy: string, timestamp: bigint];
      export interface OutputObject {accessId: bigint, flaggedBy: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyAccessGrantedEvent {
      export type InputTuple = [accessId: BigNumberish, doctor: AddressLike, patient: AddressLike, reason: string, timestamp: BigNumberish, expiresAt: BigNumberish];
      export type OutputTuple = [accessId: bigint, doctor: string, patient: string, reason: string, timestamp: bigint, expiresAt: bigint];
      export interface OutputObject {accessId: bigint, doctor: string, patient: string, reason: string, timestamp: bigint, expiresAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MedicalRecordAnchoredEvent {
      export type InputTuple = [recordId: BigNumberish, patient: AddressLike, fileHash: BytesLike, metadataHash: BytesLike, timestamp: BigNumberish];
      export type OutputTuple = [recordId: bigint, patient: string, fileHash: string, metadataHash: string, timestamp: bigint];
      export interface OutputObject {recordId: bigint, patient: string, fileHash: string, metadataHash: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProviderVerificationUpdatedEvent {
      export type InputTuple = [provider: AddressLike, verified: boolean, updatedBy: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [provider: string, verified: boolean, updatedBy: string, timestamp: bigint];
      export interface OutputObject {provider: string, verified: boolean, updatedBy: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RecordAccessedEvent {
      export type InputTuple = [accessId: BigNumberish, recordId: BigNumberish, doctor: AddressLike, patient: AddressLike, emergencyAccess: boolean, timestamp: BigNumberish];
      export type OutputTuple = [accessId: bigint, recordId: bigint, doctor: string, patient: string, emergencyAccess: boolean, timestamp: bigint];
      export interface OutputObject {accessId: bigint, recordId: bigint, doctor: string, patient: string, emergencyAccess: boolean, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface HealthRecords extends BaseContract {
    
    connect(runner?: ContractRunner | null): HealthRecords;
    waitForDeployment(): Promise<this>;

    interface: HealthRecordsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    EMERGENCY_ACCESS_DURATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_EMERGENCY_REASON_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    activeEmergencyAccessId: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    activeStandardAccessId: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    anchorMedicalRecord: TypedContractMethod<
      [fileHash: BytesLike, metadataHash: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    consent: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    expireEmergencyAccess: TypedContractMethod<
      [accessId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    flagForReview: TypedContractMethod<
      [accessId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getAccessRecord: TypedContractMethod<
      [accessId: BigNumberish, ],
      [HealthRecords.AccessRecordStructOutput],
      'view'
    >
    

    
    getMedicalRecord: TypedContractMethod<
      [recordId: BigNumberish, ],
      [HealthRecords.MedicalRecordStructOutput],
      'view'
    >
    

    
    getPatientRecordIds: TypedContractMethod<
      [patient: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    grantAccess: TypedContractMethod<
      [doctor: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    hasAccess: TypedContractMethod<
      [patient: AddressLike, doctor: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    latestPendingRequestId: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    logRecordAccess: TypedContractMethod<
      [patient: AddressLike, recordId: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    nextAccessId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    nextRecordId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    recordIdByHash: TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    rejectAccessRequest: TypedContractMethod<
      [accessId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    requestAccess: TypedContractMethod<
      [patient: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    requestEmergencyAccess: TypedContractMethod<
      [patient: AddressLike, reason: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    revokeAccess: TypedContractMethod<
      [doctor: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setVerifiedProvider: TypedContractMethod<
      [provider: AddressLike, verified: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    transferAdmin: TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    verifiedProviders: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'EMERGENCY_ACCESS_DURATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_EMERGENCY_REASON_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'activeEmergencyAccessId'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'activeStandardAccessId'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'anchorMedicalRecord'): TypedContractMethod<
      [fileHash: BytesLike, metadataHash: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'consent'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'expireEmergencyAccess'): TypedContractMethod<
      [accessId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'flagForReview'): TypedContractMethod<
      [accessId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAccessRecord'): TypedContractMethod<
      [accessId: BigNumberish, ],
      [HealthRecords.AccessRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getMedicalRecord'): TypedContractMethod<
      [recordId: BigNumberish, ],
      [HealthRecords.MedicalRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPatientRecordIds'): TypedContractMethod<
      [patient: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'grantAccess'): TypedContractMethod<
      [doctor: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasAccess'): TypedContractMethod<
      [patient: AddressLike, doctor: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'latestPendingRequestId'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'logRecordAccess'): TypedContractMethod<
      [patient: AddressLike, recordId: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'nextAccessId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nextRecordId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'recordIdByHash'): TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rejectAccessRequest'): TypedContractMethod<
      [accessId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestAccess'): TypedContractMethod<
      [patient: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestEmergencyAccess'): TypedContractMethod<
      [patient: AddressLike, reason: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeAccess'): TypedContractMethod<
      [doctor: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setVerifiedProvider'): TypedContractMethod<
      [provider: AddressLike, verified: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferAdmin'): TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifiedProviders'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'AccessGranted'): TypedContractEvent<AccessGrantedEvent.InputTuple, AccessGrantedEvent.OutputTuple, AccessGrantedEvent.OutputObject>;
getEvent(key: 'AccessRequestRejected'): TypedContractEvent<AccessRequestRejectedEvent.InputTuple, AccessRequestRejectedEvent.OutputTuple, AccessRequestRejectedEvent.OutputObject>;
getEvent(key: 'AccessRequested'): TypedContractEvent<AccessRequestedEvent.InputTuple, AccessRequestedEvent.OutputTuple, AccessRequestedEvent.OutputObject>;
getEvent(key: 'AccessRevoked'): TypedContractEvent<AccessRevokedEvent.InputTuple, AccessRevokedEvent.OutputTuple, AccessRevokedEvent.OutputObject>;
getEvent(key: 'AdminTransferred'): TypedContractEvent<AdminTransferredEvent.InputTuple, AdminTransferredEvent.OutputTuple, AdminTransferredEvent.OutputObject>;
getEvent(key: 'EmergencyAccessExpired'): TypedContractEvent<EmergencyAccessExpiredEvent.InputTuple, EmergencyAccessExpiredEvent.OutputTuple, EmergencyAccessExpiredEvent.OutputObject>;
getEvent(key: 'EmergencyAccessFlagged'): TypedContractEvent<EmergencyAccessFlaggedEvent.InputTuple, EmergencyAccessFlaggedEvent.OutputTuple, EmergencyAccessFlaggedEvent.OutputObject>;
getEvent(key: 'EmergencyAccessGranted'): TypedContractEvent<EmergencyAccessGrantedEvent.InputTuple, EmergencyAccessGrantedEvent.OutputTuple, EmergencyAccessGrantedEvent.OutputObject>;
getEvent(key: 'MedicalRecordAnchored'): TypedContractEvent<MedicalRecordAnchoredEvent.InputTuple, MedicalRecordAnchoredEvent.OutputTuple, MedicalRecordAnchoredEvent.OutputObject>;
getEvent(key: 'ProviderVerificationUpdated'): TypedContractEvent<ProviderVerificationUpdatedEvent.InputTuple, ProviderVerificationUpdatedEvent.OutputTuple, ProviderVerificationUpdatedEvent.OutputObject>;
getEvent(key: 'RecordAccessed'): TypedContractEvent<RecordAccessedEvent.InputTuple, RecordAccessedEvent.OutputTuple, RecordAccessedEvent.OutputObject>;

    filters: {
      
      'AccessGranted(uint256,address,address,uint64)': TypedContractEvent<AccessGrantedEvent.InputTuple, AccessGrantedEvent.OutputTuple, AccessGrantedEvent.OutputObject>;
      AccessGranted: TypedContractEvent<AccessGrantedEvent.InputTuple, AccessGrantedEvent.OutputTuple, AccessGrantedEvent.OutputObject>;
    

      'AccessRequestRejected(uint256,address,address,uint64)': TypedContractEvent<AccessRequestRejectedEvent.InputTuple, AccessRequestRejectedEvent.OutputTuple, AccessRequestRejectedEvent.OutputObject>;
      AccessRequestRejected: TypedContractEvent<AccessRequestRejectedEvent.InputTuple, AccessRequestRejectedEvent.OutputTuple, AccessRequestRejectedEvent.OutputObject>;
    

      'AccessRequested(uint256,address,address,uint64)': TypedContractEvent<AccessRequestedEvent.InputTuple, AccessRequestedEvent.OutputTuple, AccessRequestedEvent.OutputObject>;
      AccessRequested: TypedContractEvent<AccessRequestedEvent.InputTuple, AccessRequestedEvent.OutputTuple, AccessRequestedEvent.OutputObject>;
    

      'AccessRevoked(uint256,address,address,bool,uint64)': TypedContractEvent<AccessRevokedEvent.InputTuple, AccessRevokedEvent.OutputTuple, AccessRevokedEvent.OutputObject>;
      AccessRevoked: TypedContractEvent<AccessRevokedEvent.InputTuple, AccessRevokedEvent.OutputTuple, AccessRevokedEvent.OutputObject>;
    

      'AdminTransferred(address,address)': TypedContractEvent<AdminTransferredEvent.InputTuple, AdminTransferredEvent.OutputTuple, AdminTransferredEvent.OutputObject>;
      AdminTransferred: TypedContractEvent<AdminTransferredEvent.InputTuple, AdminTransferredEvent.OutputTuple, AdminTransferredEvent.OutputObject>;
    

      'EmergencyAccessExpired(uint256,address,address,uint64)': TypedContractEvent<EmergencyAccessExpiredEvent.InputTuple, EmergencyAccessExpiredEvent.OutputTuple, EmergencyAccessExpiredEvent.OutputObject>;
      EmergencyAccessExpired: TypedContractEvent<EmergencyAccessExpiredEvent.InputTuple, EmergencyAccessExpiredEvent.OutputTuple, EmergencyAccessExpiredEvent.OutputObject>;
    

      'EmergencyAccessFlagged(uint256,address,uint64)': TypedContractEvent<EmergencyAccessFlaggedEvent.InputTuple, EmergencyAccessFlaggedEvent.OutputTuple, EmergencyAccessFlaggedEvent.OutputObject>;
      EmergencyAccessFlagged: TypedContractEvent<EmergencyAccessFlaggedEvent.InputTuple, EmergencyAccessFlaggedEvent.OutputTuple, EmergencyAccessFlaggedEvent.OutputObject>;
    

      'EmergencyAccessGranted(uint256,address,address,string,uint64,uint64)': TypedContractEvent<EmergencyAccessGrantedEvent.InputTuple, EmergencyAccessGrantedEvent.OutputTuple, EmergencyAccessGrantedEvent.OutputObject>;
      EmergencyAccessGranted: TypedContractEvent<EmergencyAccessGrantedEvent.InputTuple, EmergencyAccessGrantedEvent.OutputTuple, EmergencyAccessGrantedEvent.OutputObject>;
    

      'MedicalRecordAnchored(uint256,address,bytes32,bytes32,uint64)': TypedContractEvent<MedicalRecordAnchoredEvent.InputTuple, MedicalRecordAnchoredEvent.OutputTuple, MedicalRecordAnchoredEvent.OutputObject>;
      MedicalRecordAnchored: TypedContractEvent<MedicalRecordAnchoredEvent.InputTuple, MedicalRecordAnchoredEvent.OutputTuple, MedicalRecordAnchoredEvent.OutputObject>;
    

      'ProviderVerificationUpdated(address,bool,address,uint64)': TypedContractEvent<ProviderVerificationUpdatedEvent.InputTuple, ProviderVerificationUpdatedEvent.OutputTuple, ProviderVerificationUpdatedEvent.OutputObject>;
      ProviderVerificationUpdated: TypedContractEvent<ProviderVerificationUpdatedEvent.InputTuple, ProviderVerificationUpdatedEvent.OutputTuple, ProviderVerificationUpdatedEvent.OutputObject>;
    

      'RecordAccessed(uint256,uint256,address,address,bool,uint64)': TypedContractEvent<RecordAccessedEvent.InputTuple, RecordAccessedEvent.OutputTuple, RecordAccessedEvent.OutputObject>;
      RecordAccessed: TypedContractEvent<RecordAccessedEvent.InputTuple, RecordAccessedEvent.OutputTuple, RecordAccessedEvent.OutputObject>;
    
    };
  }