/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HealthRecords } from './HealthRecords.js';
export * as factories from './factories/index.js';
export { HealthRecords__factory } from './factories/HealthRecords__factory.js';